// Generated by LiveScript 1.4.0
(function(){
  var optionator, create, _, execute;
  optionator = require('./options');
  create = require('./index');
  _ = require('prelude-ls');
  execute = function(args){
    var options;
    options = optionator.parseArgv(process.argv);
    if (args === null) {
      error("you must specify arguments");
      exit(2);
      return;
    }
    if (options.help) {
      return console.log(optionator.generateHelp());
    } else if (options.run) {
      return create.run(_.last(process.argv));
    } else if (options.list) {
      if (process.argv[3]) {
        return create.list().then(function(res){
          var arrayOfLanguages, languages;
          arrayOfLanguages = _.split(',', res);
          languages = _.split(',', process.argv[3]);
          if (_.empty(_.difference(languages, arrayOfLanguages))) {
            return console.log("Yes, those are all valid languages");
          } else {
            return console.log("One or more of those languages are invalid");
          }
        });
      } else {
        return create.list().then(function(res){
          return console.log(res);
        });
      }
    }
  };
  module.exports.execute = execute;
}).call(this);
