// Generated by LiveScript 1.4.0
(function(){
  var optionator, create, _, execute;
  optionator = require('./options');
  create = require('./index');
  _ = require('prelude-ls');
  execute = function(args){
    var options;
    options = optionator.parseArgv(process.argv);
    if (args === null) {
      error("you must specify arguments");
      exit(2);
      return;
    }
    if (options.help) {
      return console.log(optionator.generateHelp());
    } else if (options.run) {
      return create.run(_.last(process.argv));
    }
  };
  module.exports.execute = execute;
}).call(this);
