// Generated by LiveScript 1.4.0
(function(){
  var optionator, create, _, execute;
  optionator = require('./options');
  create = require('./index');
  _ = require('prelude-ls');
  execute = function(args){
    var options;
    options = optionator.parseArgv(process.argv);
    if (args === null) {
      error("you must specify arguments");
      exit(2);
      return;
    }
    if (options.help) {
      return console.log(optionator.generateHelp());
    } else if (options.run) {
      return create.run(_.last(process.argv));
    } else if (options.list) {
      if (process.argv[3]) {
        return create.list().then(function(res){
          var arrayOfLanguages;
          arrayOfLanguages = _.split(',', res);
          if (_.elemIndex(process.argv[3], arrayOfLanguages)) {
            return console.log("Yes this is a valid language");
          } else {
            return console.log("This is not a valid language");
          }
        });
      } else {
        return create.list().then(function(res){
          return console.log(res);
        });
      }
    }
  };
  module.exports.execute = execute;
}).call(this);
