// Generated by LiveScript 1.4.0
(function(){
  var fs, https;
  fs = require('fs');
  https = require('https');
  module.exports.run = function(languages){
    var options, req;
    options = {
      host: 'www.gitignore.io',
      path: '/api/'.concat(languages, '/')
    };
    req = https.get(options, function(res){
      res.setEncoding('utf8');
      console.log("Hello1");
      return res.on('data', function(chunk){
        console.log("Hello2");
        if (chunk) {
          fs.unlinkSync('.gitignore', chunk);
          fs.appendFileSync('.gitignore', chunk);
          return console.log("gitignore saved!");
          return fs.closeSync('.gitignore');
        }
      });
    });
    req.on('error', function(e){
      return console.log(e.message);
    });
    return req.end();
  };
}).call(this);
