// Generated by LiveScript 1.4.0
(function(){
  var fs, request;
  fs = require('fs');
  request = require('request');
  module.exports.run = function(languages){
    return request('https://www.gitignore.io/api/'.concat(languages, '/')).pipe(fs.createWriteStream('.gitignore'));
  };
}).call(this);
