// Generated by LiveScript 1.4.0
(function(){
  var fs, request;
  fs = require('fs');
  request = require('request');
  module.exports.run = function(languages){
    request('https://www.gitignore.io/api/'.concat(languages, '/')).pipe(fs.createWriteStream('.gitignore'));
  };
  module.exports.list = function(){
    return new Promise(function(res, rej){
      return request('https://www.gitignore.io/api/list', function(error, response){
        return res(response.body);
      });
    });
  };
}).call(this);
